### ISSUE TITLE
As an unregistered user, I want to be able to register as a prime user with my chosen credentials (i.e., username and password that are both not empty words) to leverage/use services and information that are exclusively available to registered users.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#11]
- [ ] #92 the user is automatically logged in. 
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#99
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#100
- [x] #153
