### ISSUE TITLE
As a player that has entered the single player mode, I want to be able to choose the difficulty level of the game by myself so that the game would be suitable to my level.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#14]
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#101
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#103
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#47
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#25
