### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Linsey-Sue** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#165]
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#95
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#96
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#98
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#97
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#104
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#118
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#140
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#124
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#125
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#127
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#213
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#130
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#131
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#148
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#197
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#198
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#151
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#152
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#154
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#155
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#159
