### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by Linsey-Sue** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#166]
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#99
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#100
- [x] sopra-fs23-group-16/sopra-fs23-HanZikon-client#101
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#102
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#103
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#105
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#110
- [x] sopra-fs23-group-16/sopra-fs23-HanZikon-client#141
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#122
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#123
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#144
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#199
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#200
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#204
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#205
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#153
