### ISSUE TITLE
As a participant who has joined a room, I want to prepare myself in the waiting page.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#22]
**Acceptance Criteria**:
-Upon a successful joining, a list of participants is shown, the data of each of them include: picture,username, ready status;
-As a logged-in user, the username on display is your username; as an unregistered user, the random username is assigned by the system;
-By clicking on the "ready/cancel" button, you can change your ready status;
-(optional) If the owner allows, the  participant can also share the inviting link by clicking on the share button.

**Priority**: medium
**Estimate**: 24h

**Devemopment Tasks**:
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#41
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#40
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#68
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#38
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#39
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#75
