### ISSUE TITLE
(Multiple choice game) As a player in a multiple-player game, I want to play the game and give/get the feedback.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#23]
**Acceptance Criteria:**
• When the game starts, apart from the game body, the information can be seen: self
username, ranking (e.g.2/4) and points.
• The game body contains three stages in each game round (question): to learn about the
character and observe how it’s written, to rewrite it on your own, to see the original
character and everyone else’s writings.
• When you are in the third stage, you are given a grade from the system, and you can
also vote for the ‘best’ upon clicking on the writing of someone’s.
• When all questions are over, the users are redirected to a ranking page.

**Priority:** critical
**Estimate:** 20h

**Devemopment Tasks:**
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#41
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#89
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#69
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#83
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#71
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#68
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#72
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-server#138
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#74
- [ ] sopra-fs23-group-16/sopra-fs23-HanZikon-client#73
