### ISSUE TITLE
As a player participating in a multiple-player game, I want to view the game result.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#24]
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#91
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#34
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#98
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#30
