### ISSUE TITLE
As a unregistered user, I want to be able to play the game in a tourist mode and without extra information provided to leverage/use services and information that are available to the tourist user

### ISSUE THREAD

**Issue by feji08** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#6]
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#4
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#8
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#3
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#2
