### ISSUE TITLE
As a room creator and owner, I want to manage the participants in the waiting page.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#82]
**Acceptance Criteria:**
• Upon a successful room creation, a new room is shown and there are correct numbers of places for participants.
• By clicking on the game-setting button, the creator can have these options: to modify initial game setting, to view the room number and share it, (optional) to share the inviting link.
• If the setting is modified, the backend should be notified and change accordingly.
• By clicking the manage button, the creator can kick some participant out of the room upon confirmation.
• If exists, the kicked-out participants should also be excluded from the Players.
• When all participants are ready, the creator can start the game, all users are redirected to the game page.
• All the players and the final parameters of the game would be used to create a game.

**Priority**: critical
**Estimate**: 8h

**Development Tasks**: 
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#48
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#49
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#80
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#60
- [ ] sopra-fs23-group-16/sopra-fs23-template-server#81
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#62
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#67
