### ISSUE TITLE
As a registered user, I want to join a room to start a multiple-player game.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#83]
**Acceptance Criteria**:
• A tourist can see two options: to create a new room and to join an existing room.
• Only the ”join a room” function is clickable and accesible to tourists.
• By clicking on the ”Join a room” button, you are redirected to a joining room page.
• The joining room page requires you to fill in the room number and an optional password.
• Upon a successful joining, the user is redirected to a waiting page.
• The user is also uniquely represented in the backend.
• (Optional) By clicking a link from outside of this app, a user can join a room and be redirected to a waiting page.

**Priority**: critical
**Estimate**: 4h

**Development Tasks**:
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#51
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#52
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#66
