### ISSUE TITLE
As a logged-in user, I would be able to create a room to start a multiple-player game.

### ISSUE THREAD

**Issue by fitzlithepius** [sopra-fs23-group-16/sopra-fs23-HanZikon-server#90]
**Acceptance Criteria**:
• A user can see two options of starting a game: to create a new room and to join an existing room.
• ”Create a room” function can only be accessible to logged-in users, visitors will be suggested to be redirected to the log-in page if they want to access such features.
• By clicking on the ”Create a room” button, you are redirected to a game setting page.
• The game setting page contains the following fields: number of participants, game difficulty, number of questions, type of questions, room password(optional), invitation privileges(optional).
• Upon a successful creation, the user is redirected to a waiting room.

**Priority**: critical
**Estimate**: 8h

**Devemopment Tasks**: 
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#46
- [x] sopra-fs23-group-16/sopra-fs23-template-client#45
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#44
- [ ] sopra-fs23-group-16/sopra-fs23-template-client#42
- [x] sopra-fs23-group-16/sopra-fs23-template-server#85
- [x] #105
- [x] #106
- [x] #107
- [x] #108
- [x] #113
- [x] #114
